# a
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Morupara

Resources:
  Ruby1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.5
      Timeout: 10000

  Ruby2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.5
      Timeout: 10000

  Ruby3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.7
      Timeout: 10000

  Node12:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/node-npm/
      Handler: handler.main
      Runtime: nodejs12.x
      Timeout: 10000

  Node10:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/node-npm/
      Handler: handler.main
      Runtime: nodejs10.x
      Timeout: 10000

  Node12Yarn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/node-yarn/
      Handler: handler.main
      Runtime: nodejs12.x
      Timeout: 10000
