# a
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Morupara

Resources:
  Ruby27:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.7
      Timeout: 10000

  Ruby32:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby3.2
      Timeout: 10000
