# a
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Morupara

Resources:
  Ruby2_5:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.5
      Timeout: 10000

  Ruby2_7:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby2.7
      Timeout: 10000

  Ruby3_2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ruby/
      Handler: handler.main
      Runtime: ruby3.2
      Timeout: 10000
